transe_11_juin/apps/pong/urls.py
"""Definir des motifs d'URL pour le site pong"""

from django.urls    import path
from .              import views

app_name = 'pong'

urlpatterns = [
    # Page d'accueil:
    path('', views.index, name='index'),

    # Page d'affichage des détails d'un seul User.
    path('profil/', views.profil, name='profil'),

    # Page d'ajout d'un nouveau profil.
    path('new_profil/', views.new_profil, name='new_profil'),

    # Page d'affichage du jeux pong.
    path('pong/', views.pong, name='pong'),
    
    # Page de suppression User et ses données.
    path('del_user/', views.del_user, name='del_user'),
]

transe_11_juin/apps/utilisateurs/urls.py
"""Definir des motifs d'URL pour utilisateurs"""

from django.urls    import path, include
from .              import views

app_name = 'utilisateurs'

urlpatterns = [
    # Inclure les URL d'auhtentification par défault:
    path('',include('django.contrib.auth.urls')),
    
    # Page d'inscription:
    path('register/', views.register, name='register'),
]

transe_11_juin/apps/website/urls.py
from django.contrib import admin
from django.urls    import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('utilisateurs/', include('utilisateurs.urls')),
    path('', include('pong.urls')),
]

transe_11_juin/apps/pong/models.py
from django.db                      import models
from django.core.validators         import MinLengthValidator
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models     import User


class Player(models.Model):
    """Informations concernant l'utilisateurs"""

    # Fixe automatiquement l'heure courante lors de la creation d'un nv User:
    date_added = models.DateTimeField(auto_now_add=True)

    nickname = models.CharField(
        max_length=20, verbose_name="nickname", 
        validators=[MinLengthValidator(2, message="the nickname should have at least 2 characters.")],
    )
  
    wins = models.IntegerField(blank=True, default='0')
    loses = models.IntegerField(blank=True, default='0')

    tourPos = ArrayField(models.IntegerField(null=True, blank=True), null=True, blank=True)
    tourAll = ArrayField(models.IntegerField(null=True, blank=True), null=True, blank=True)

    duelMyname = ArrayField(models.CharField(null=True, blank=True),null=True, blank=True)
    duelEnemy = ArrayField(models.CharField(null=True, blank=True),null=True, blank=True)
    duelMe = ArrayField(models.IntegerField(null=True, blank=True),null=True, blank=True)
    duelThem = ArrayField(models.IntegerField(null=True, blank=True),null=True, blank=True)

    FriendsId = ArrayField(models.IntegerField(null=True, blank=True),null=True, blank=True)

    LANGUAGE_CHOICES = (
        ('EN', 'english'),
        ('ES', 'spanish'),
        ('FR', 'french'),
    )
 
    language = models.CharField(max_length=2, choices=LANGUAGE_CHOICES)

    # Supprime tous les éléments liées a l'utilisateur:
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Profil: {self.nickname} - User: {self.owner}'
    def clean(self):
        super().clean()

transe_11_juin/apps/utilisateurs/models.py
from django.db import models

# Create your models here.

transe_11_juin/apps/pong/forms.py
from django import forms

from .models import Player

class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ['nickname', 'language']
        labels = {'nickname': 'Pseudo', 'language': 'language'}

transe_11_juin/apps/pong/views.py
from django.shortcuts               import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions         import ObjectDoesNotExist
from .models                        import Player
from .forms                         import PlayerForm

 
def _get_profil(request):
    """Verife que le profil du User existe."""

    try:
        return Player.objects.get(owner=request.user)
    except ObjectDoesNotExist:
        return None
    

# Create your views here.
def index(request):
    """La page d'accueil pour PONG."""

    return render(request, 'pong/index.html')

 
@login_required
def profil(request):
    """Afficher un seul User et toutes ses donn€es."""

    profil = _get_profil(request)
    if profil == None:
        return redirect('pong:new_profil')

    # profil = Player.objects.get(owner=request.user)
    players = Player.objects.all()
    context = {'profil': profil, 'players': players}
    return render(request, 'pong/profil.html', context)


def new_profil(request):
    """Ajoute un nouvel utilisateur et son profil."""

    if request.method != 'POST':
        # Afficher un formulaire d'inscription vide:
        form = PlayerForm()
    else:
        # Traiter le formulaire rempli et renvoie a l'accueil:
        form = PlayerForm(data=request.POST)
        players = Player.objects.all()
        if form.is_valid:
            profil = form.save(commit=False)
            # Verifie si le nickname est deja pris:
            for player in players:
                if player.nickname == profil.nickname:
                    return redirect('pong:new_profil')
            profil.owner = request.user
            profil.save()
            return redirect('pong:index')
        
    # Afficher un formuliare vierge ou invalide:
    context = {'form': form}
    return render(request, 'pong/new_profil.html', context)


@login_required
def del_user(request):
    """Supprime un utilisateur et supprime ses donn€es."""
    
    user = request.user
    user.delete()
    return redirect("pong:index")


@login_required
def pong(request):
    """Page du jeux Pong."""
    
    player = _get_profil(request)
    if player == None:
        return redirect('pong:new_profil')
    
    players = Player.objects.all()
    # player = Player.objects.get(owner=request.user)
    return render(request, "pong/pong.html",  { 'players':players, 'player':player})

 

transe_11_juin/apps/utilisateurs/views.py
from django.shortcuts           import render, redirect
from django.contrib.auth        import login
from django.contrib.auth.forms  import UserCreationForm



# Create your views here.
def register(request):
    """Inscrire un nouvel utilisateur."""
    if request.method != 'POST':
        # Afficher un formulaire d'inscription vide:
        form = UserCreationForm()
    else:
        # Traiter le formulaire rempli:
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Ouvrir session de l'utilisateur et diriger vers la page profil:
            login(request, new_user)
            return redirect('pong:new_profil')
        
    # Afficher un formuliare vierge ou invalide:
    context = {'form': form}
    return render(request, 'registration/register.html', context)
         

transe_11_juin/apps/pong/templates/pong/base.html
{% load static %}
{% load django_bootstrap5 %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,
        initial-scale=1, shrink-to-fit=no">
        <title>Pong, the Rematch</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>


    <body>

        <!-- Section de page reservee au liens de navigations. -->
        <nav class="navbar navbar-expand-md navbar-light bg-light
            mb-4 border">
          
            <div class="container-fluid">
                <!-- Lien vers la page d'accueil en haut a gauche. -->
                <a class="navbar-brand" href="{% url 'pong:index' %}        ">Home</a>

                <!-- Affiche un boutton si ecran trop petit. -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                    
                <!-- liens compris dans le bouton. -->
                <div class="collapse navbar-collapse"       id="navbarNavAltMarkup">
                    <!-- Lien profil. -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'pong:profil' %}">Profil</a> 
                        </li>
                    </ul> 
                    <!-- Lien Pong. -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'pong:pong' %}
                            ">Pong</a> 
                        </li>
                    </ul> 
                    <!-- si Utilsateur connecté. -->
                    <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <!-- Lien deconnexion. -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'utilisateurs:logout' %}">Logout</a>
                        </li>
  
                    {% else %}
                        <!-- Lien inscription. -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url            'utilisateurs:register' %}">Sign-up</a>
                        </li>
                        <!-- Lien connexion. -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'utilisateurs:login' %}">Login</a>
                        </li>
                    {% endif %}
                    </ul>
                </div>
            </div>
            
        </nav>


        <!-- Définit la zone principale de la page. -->
        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>
        
    </body>
    
    <script src="{% static 'pong.js' %}"></script>

</html>

transe_11_juin/apps/pong/templates/pong/index.html
{% extends "pong/base.html" %}

{% block page_header %}

    <div class="jumbotron">
        <h1 class="display-3">Pong the Rematch</h1>

        <p class="lead">
            Bienvenue sur PONG! ce site permet de jouer a pong en multijoueur!
            Faire des matchmaking et inclus aussi l'hitorique de partie et amis
        </p>

        {% if user.is_authenticated %}
            <p>Content de vous voir {{ user.username }} !</p>
        {% else %}
            <div class="nav-item">
                <a class="btn btn-lg btn-primary" href="{% url 'utilisateurs:register' %}">Sign-up &raquo;</a>
            </div>

        {% endif %}
    </div>

{% endblock page_header %}

transe_11_juin/apps/pong/templates/pong/new_profil.html
<p>
    <h1>Bonjour {{ user.username }}.</h1>
</p>

<form method="post" action="{% url 'pong:new_profil' %}" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Renseignez votre profil.</button>

</form>

transe_11_juin/apps/pong/templates/pong/pong.html
{% extends 'pong/base.html' %}
{% load static %}
{% block content %}
<body>


<p>JEUX</p>

    <button lang="fr" id = 'btnCreateSolo'>Nouvelle partie</button>
    <button lang="fr" id = 'btnCreate2Player'>Nouvelle partie Multi</button>
    <canvas class="canva"></canvas>


    <script>

    </script>

    <script type="text/javascript" src="{% static "pong.js" %}"></script>


</body>
{% endblock %}

transe_11_juin/apps/pong/templates/pong/profil.html
{% extends "pong/base.html" %}


{% block content %}
    
    <h1>Hello {{ profil.owner }}, bienvenue sur ton profil.</h1>

    <div>
        ATTENTION: la supression du profil est definitive !
        <a href="{% url 'pong:del_user' %}">Suppression</a>
    </div>

    <h3>date de creation: {{ profil.date_added|date:'d F Y, H:i' }}</h3>

    <ul>
        <li><strong>Pseudo:</strong> {{ profil.nickname }}</li>
        <li><strong>Wins:</strong> {{ profil.wins }}</li>
        <li><strong>Loses:</strong> {{ profil.loses }}</li>

        <li><strong>Tournament position:</strong>
            {% for position in profil.tourPos %}
                {{ position }}  /
            {% empty %}
                None
            {% endfor %}
        </li>

        <li><strong>My name in duel :</strong>
            {% for name in profil.duelmyName %}
                <li>{{ name }}
            {% empty %}
                <li>None
            {% endfor %}
                </li>
        </li>

        <li><strong>Ennemy's duel name:</strong>
            {% for enemy in profil.duelEnemy %}
                <li>{{ enemy }}
            {% empty %}
                <li>None
            {% endfor %}
        </li>
        
        </li>

        <li><strong>Duel me:</strong>
            {% for me in profil.duelme %}
                {{ me }}  /
            {% empty %}
               None
            {% endfor %}
        </li>

        <li><strong>Duel them:</strong>
            {% for them in profil.duelthem %}
                {{ them }}  /
            {% empty %}
                None
            {% endfor %}
        </li>

        <li><strong>Friend's ID:</strong>
            {% for friend in profil.friendsId %}
                {{ friend }}  /
            {% empty %}
                Empty
            {% endfor %}
        </li>

        <li><strong>language:</strong> {{ profil.language }}</li>
    </ul>
{% endblock content %}